vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

require 'config/options'
require 'config/keymaps'
-- require 'config/lsp'

require 'plugins/oil'
require 'plugins/autopairs'
require 'plugins/colorschemes'
require 'plugins/which-key'
require 'plugins/snacks'
require 'plugins/treesitter'
require 'plugins/mason'
require 'plugins/neotest'
require 'plugins/dap'
require 'plugins/gitsigns'
require 'plugins/flash'
require 'plugins/markdown'
require 'plugins/zk'
require 'plugins/blink'
require 'plugins/conform'
require 'plugins/lsp'
